unit RandomTestLinkedList;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Lists, System.SysUtils;

type
  // Test methods for class TLinkedList

  TestTLinkedList = class(TTestCase)
  strict private
    FLinkedList: TLinkedList;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure RandomTests;
  end;

implementation

procedure TestTLinkedList.SetUp;
begin
  FLinkedList := TLinkedList.Create;
  Randomize;
end;

procedure TestTLinkedList.TearDown;
begin
  FLinkedList.Free;
  FLinkedList := nil;
end;

procedure TestTLinkedList.RandomTests;
var
  Action, ReturnValue, k: Integer;
  BoolReturnValue : Boolean;
  pos, a: Integer;
  I: Integer;
begin
  FLinkedList := TLinkedList.Create;
//  FArrList := TArrList.Create;
  k := 0;
  for I := 0 to 500 do
  begin
    Action := Random(5);
    case Action of
      0:
      begin
        a := Random(100);
        ReturnValue := FLinkedList.Add(a);
//        ReturnValue := FArrList.Add(a);
        CheckEquals(FLinkedList.Count, ReturnValue + 1, 'Unexpected list count after Add');
        Inc(k);
      end;
      1:
      begin
        pos := Random(FLinkedList.Count + 10);
        a := Random(100);
        BoolReturnValue := FLinkedList.Insert(pos, a);
        CheckEquals((pos >= 0) and (pos < FLinkedList.Count), BoolReturnValue, 'Unexpected return value after Insert');
        if BoolReturnValue then
        begin
          Inc(k);
        end;
        CheckEquals(k, FLinkedList.Count, 'Unexpected list count after Insert');
      end;
      2:
      begin
        pos := Random(30);
        BoolReturnValue := FLinkedList.Delete(pos);
        CheckEquals((pos >= 0) and (pos < k), BoolReturnValue, 'Unexpected return value after Delete');
        if BoolReturnValue then
        begin
          Dec(k);
        end;
        CheckEquals(k, FLinkedList.Count, 'Unexpected list count after Delete');
      end;
      3:
      begin
        FLinkedList.Clear;
        CheckEquals(0, FLinkedList.Count, 'Unexpected non-empty array');
        k := 0;
      end;
      4: CheckEquals(k, FLinkedList.Count, 'Unexpected list count after CheckCount');
    end;

  end;


end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTLinkedList.Suite);
end.

